/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        'introduction',
        {
            type: 'category',
            label: 'Products',
            link: {
                type: 'generated-index',
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'products',
                },
            ],
        },
    ],
    developer: [
        'developer',
        {
            type: 'category',
            label: 'Release Guidelines',
            link: {
                type: 'generated-index',
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'release',
                },
            ],
        },
        'github-checks'
    ],
    kits: [
        // 'kits',
        // {
        //     type: 'autogenerated',
        //     dirName: 'kits',
        // },

        // _____ Option 1 ______
        // {
        //     type: 'category',
        //     label: 'Our Kits',
        //     link: {
        //         type: 'generated-index',
        //     },
        //     collapsed: true,
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'kits',
        //         },
        //     ],
        // },

        // // _____ Option 2 ______
        {
            type: 'category',
            label: 'Business Partner Kit',
            link: {
                type: 'generated-index',
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'kits/Business Partner Kit',
                },
            ],
        },
        {
            type: 'category',
            label: 'Data Chain Kit',
            link: {
                type: 'generated-index',
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'kits/Data Chain Kit',
                },
            ],
        },
    ],
};

module.exports = sidebars;
