/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        'developer',
        'getting-started',
        {
            type: 'category',
            label: 'Open Source Development',
            link: {
                type: 'generated-index',
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'oss',
                },
            ],
        },
        {
            type: 'category',
            label: 'Release Guidelines',
            link: {
                type: 'doc',
                id: 'release'
            },
            collapsed: true,
            items: [
                {
                    type: 'category',
                    label: 'TRG 0 - Drafts',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-0',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 1 - Documentation',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-1',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 2 - GIT',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-2',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 3 - Kubernetes',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-3',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 4 - Container',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-4',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 5 - Helm',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-5',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 6 - Artefacts',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-6',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 7 - Open Source Governance',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-7',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 8 - Security',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-8',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 9 - UX/UI Styleguide',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-9',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'TRG 10 - Keep it Together (KITs)',
                    link: {
                        type: 'generated-index',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'release/trg-10',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Website Admin Guidelines',
            link: {
                type: 'doc',
                id: "website-guidelines/wiki",
            },
            collapsed: true,
            items: [
                "website-guidelines/create-open-api-doc",
                "website-guidelines/understanding-multi-instance_versioning",
                "website-guidelines/update-and-integrate-react-components",
                "website-guidelines/update-news-page",
                "website-guidelines/automate-kit-doc-update",
                "website-guidelines/kit-structure",
            ],
        },
        'github-checks',
        'dev_faq',
        'dev_links'
    ],
    tutorials: [
        'tutorials',
        {
            type: 'category',
            label: 'End-to-End Adopter Journey',
            link: {
                type: 'doc',
                id: 'tutorials/e2e'
            },
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials/e2e',
                },
            ],
        },
        'tutorials/identity-hub'
    ],
};

module.exports = sidebars;
