/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'developer',
      {
          type: 'category',
          label: 'Release Guidelines',
          link: {
              type: 'doc',
              id: 'release'
          },
          collapsed: true,
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'release',
              },
          ],
      },
      {
          type: 'category',
          label: 'KIT Guidelines',
           link: {
               type: 'doc',
               id: 'kit-process/coverpage'
           },
          collapsed: true,
          items: [
              "kit-process/graduation-process",
              "kit-process/versioning",
              "kit-process/artefacts",
              {
                type: 'category',
                label: "FAQ",
                link: {
                    type: "doc",
                    id: "kit-process/processes/coverpage"
                },
                collapsed: true,
                items: [
                    "kit-process/processes/contribute",
                    "kit-process/processes/create_KIT_page",
                    "kit-process/processes/update-documentation",

                ]
              } 
          ],
      },{
        type: 'category',
        label: 'Website Admin Guidelines',
        link: {
            type: 'doc',
            id: 'website-guidelines/coverpage'
        },
        collapsed: true,
        items: [
            "website-guidelines/dev_faq",
            "website-guidelines/wiki",
        ],
    },
      {
          type: 'category',
          label: 'Open Source Development',
          link: {
              type: 'generated-index',
          },
          collapsed: true,
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'oss',
              },
          ],
      },
      'github-checks',
      'dev_links'
  ],
};

module.exports = sidebars;
