@startuml "PCF Request alternative approaches"
!startsub GetAssetViaTwin
group Extract EDC call from submodel
PCF_Client -> PCF_Client: Extract Endpoint from submodel via 'idShort'
PCF_Client -> PCF_Client: Rewrite endpoint URL for call through own API Wrapper
end
!endsub

!startsub GetAssetViaType
group Discover PCF Asset via Type
PCF_Client -> Client_EDC: Lookup Companies PCF Exchange Asset\n(via Company's EDC URL)
Client_EDC -> Company_EDC: Lookup Asset in Catalog\n(EDC asset type "data.pcf.exchangeEndpoint")
note left
There could be multiple EDC URLs, but
only one with a PCF Exchange Asset
end note
Company_EDC -> Client_EDC: PCF Asset
Client_EDC -> PCF_Client: PCF Asset ID
end
!endsub

@enduml