@startuml

autonumber "<B>[00]"
autoactivate on

box "Sender"
participant "Some (Traceability) App" as TraceApp1 order 0
participant "Notification EDC Adapter" as NAdapter order 1
rnote right NAdapter
Not mandatory as the interaction
with the EDC can be implemented
also in the (Traceability) App.

However, a similar functionality
(e.g., fetch catalog)
- as shown below - must be
provided.
end rnote
participant "EDC" as SEDC order 2
end box
participant "Discovery Service" as SD order 3
box "Receiver"
participant "EDC" as REDC order 4
participant "Some (Traceability) App" as TraceApp2 order 5
end box
TraceApp2 -> REDC: Create EDC Asset for \n"Quality Alert Update"\nwith ""DataAddress"" as ""HTTP POST"" endpoint
return OK
TraceApp1 -> TraceApp1: Change Notification\n(e.g., Status according Status Model)
deactivate TraceApp1
TraceApp1 -> SD: Resolve EDC Endpoint
rnote right TraceApp1
BPN of supply chain partner (as given in existing notification)
end rnote
return OK
TraceApp1 -> NAdapter: Send Notification **Update**
rnote right TraceApp1
Payload as described above.
end rnote
NAdapter -> SEDC: Fetch Catalog
SEDC <-[dashed]-> REDC: Fetch Catalog
NAdapter -> NAdapter: Find and Select Contract
rnote right NAdapter
Find the correct contract offer with:

"dct:type": {
      "@id": "cx-taxo:UpdateQualityAlertNotification"
    }"
end rnote
deactivate NAdapter
NAdapter -> SEDC: Intiatiate Contract Negotiation
SEDC <-[dashed]-> REDC: Contract Negotiation
NAdapter -> SEDC: Inititate Data Transfer
SEDC <-[dashed]-> REDC: Establish Channel
NAdapter -> SEDC: POST /public/...
rnote right NAdapter
Payload as described above.
end rnote
SEDC -> REDC: POST /public/...
rnote right SEDC
Payload as described above.
end rnote
REDC -> TraceApp2: POST /notifications/qualityalerts/update
rnote right REDC
Payload as described above.
end rnote
rnote right REDC
The http path depends on the DataAddress
in the EDC Data Asset. Thus, it depends on the
(Trace) app.
end rnote
TraceApp2 -[dashed]->REDC: ""200"" OK
REDC -[dashed]-> SEDC: ""200"" OK
SEDC -[dashed]-> NAdapter: ""200"" OK
NAdapter -[dashed]-> TraceApp1: ""200"" OK
@enduml