---
config:
    treeView:
        rowIndent: 55
        lineThickness: 2
    themeVariables:
        treeView:
            labelFontSize: '15px'
---
treeView-beta
    "Manufacturing Data Model"
        "General Production Data (CommonParameter)"
            "Time Planning (Scheduled & Actual)"
            "Identification (Work Order, Product, Location)"
            "Sustainability (CO₂ Footprint)"
        "Process-Specific Data (BillOfProcess)"
            "Machine Assignment & Configuration"
            "Quantity Management (Planned, Produced, Scrapped)"
            "Resource Consumption (Energy & Materials)"
            "Environmental Impact (Process CO₂)"