openapi: 3.0.1
info:
  title: Business Partner Data Management Bridge Dummy
  description: Bridge between Gate and Pool as a simple replacement for a dedicated sharing service
  version: 5.0.1-SNAPSHOT
servers:
  - url: http://localhost:8083
    description: Generated server url
paths:
  /api/bridge/sync:
    post:
      tags:
        - bridge-controller
      summary: Start sync between Gate and Pool
      operationId: triggerSync
      responses:
        '200':
          description: OK
components: {}
