openapi: 3.0.1
info:
  title: Business Partner Data Management Cleaning Service Dummy
  description: Place holder for the cleaning service provider
  version: 4.1.0-SNAPSHOT
servers:
  - url: http://localhost:8084
    description: Generated server url
paths: {}
components: {}
