---
title: Knowledge_Agents Branching Strategy
---
gitGraph
    commit
    commit
    branch "release/1.0.x"
    checkout "release/1.0.x"
    commit id: "ver(1.0.0)" tag: "1.0.0"

    checkout main
    commit id: "ver(0.1.0-SNAPSHOT)"
    commit id: "fix(A)"
    commit
    checkout "release/1.0.x"
    branch "fix/1.0.x/A"
    cherry-pick id: "fix(A)"
    checkout "release/1.0.x"
    merge "fix/1.0.x/A"

    checkout "release/1.0.x"
    commit id: "ver(1.0.1)" tag: "1.0.1"
    checkout main
    commit
    commit
    branch "release/1.1.x"
    checkout "release/1.1.x"
    commit id: "ver(1.1.0)" tag: "1.1.0"
    checkout main
    commit id: "ver(1.2.0-SNAPSHOT)"
    commit
    commit id: "ver(2.0.0-SNAPSHOT)"
    branch "feat(B)"
    commit id: "feat(B)"
    checkout main
    branch "fix/C"
    commit id: "fix(C)"

