openapi: 3.0.1
info:
  title: Notification API
  description: Notification API
  license:
    name: Apache License v2.0
    url: http://apache.org/v2
  version: 1.1.0
servers:
- url: /
tags:
- name: Notification API
  description: 'Api to receive, update and fetch a notification. At the moment, quality notifications are supported. Those support two types of quality notifications: quality investigations and quality alerts.'
paths:
  /qualitynotifications/receive:
    post:
      tags:
      - Quality notification
      description: Receives a new quality notification
      operationId: receiveQualityNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityNotificationReceiveRequestBody'
      responses:
        "201":
          description: Quality notification was received successfully
        "400":
          description: Request body was malformed
        "401":
          description: Not authorized     
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "409":
          description: Could not accept the send quality notification, because a quality notification with that notificationId already exists
        "422":
          description: Could not accept the send quality notification even though it is syntactically correct. The quality notification is not accepted, because of semantic reasons (e.g., an affected item is not known by the receiver).
  /qualitynotifications/update:
    post:
      tags:
      - Quality notification
      description: Updates a quality notification
      operationId: updateQualityNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityNotificationUpdateRequestBody'
      responses:
        "200":
          description: Quality notification was updated successfully
        "400":
          description: Request body was malformed
        "401":
          description: Not authorized     
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "404":
          description: Could not update the quality notification, because a quality notification with that notificationId does not exist
        "422":
          description: Could not update the quality notification even though the request is syntactically correct. The quality notification update is not accepted, because of semantic reasons (e.g., status cannot be changed).
  /qualitynotifications/resolve:          
    post:
      tags:
      - Quality notification
      description: Resolves a quality notification
      operationId: getQualityNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityNotificationGetRequestHeader'        
      responses:
        "200":
          description: Quality notification was resolved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityNotificationGetResponseHeader'
        "400":
          description: Request body was malformed
        "401":
          description: Not authorized     
        "403":
          description: Forbidden
        "404":
          description: Could not resolve the quality notification, because a quality notification with that notificationId does not exist
        "405":
          description: Method not allowed
components:
  schemas:
    QualityNotificationReceiveRequestHeader:
      type: object
      required:
        - notificationId
        - senderBPN
        - senderAddress
        - recipientBPN
        - classification
        - severity
        - status
        - messageId
      properties:
        notificationId:
          type: string
          format: uuid
          example: "a7954026-3aff-4b6c-92bf-04671ef2fa46"
          description: A UUIDv4 to uniquely identify a quality notification.
        senderBPN:
          type: string
          example: "BPNL00000003BW3S"
          description: The business partner number (BPN) of the sender.
        senderAddress:
          type: string
          format: uri
          example: "https://edc.company-xyz.io/BPNL00000003BW3S"
          description: The Eclipse Dataspace Connector (EDC) URL of the sender.
        recipientBPN:
          type: string
          example: "BPNL00000003BV4H"
          description: The business partner number (BPN) of the receiver.
        classification:
          $ref: '#/components/schemas/QualityClassification'
        severity:
          $ref: '#/components/schemas/QualitySeverity'
        relatedNotificationId:
          type: string
          format: uuid
          example: "7895a39d-c4ef-4b75-b39f-cae8207a262f"
          description: A UUIDv4 to uniquely identify a related quality notification.
        status:
          $ref: '#/components/schemas/QualityStatus'
        targetDate:
          type: string
          format: date-time
          example: "2022-07-28T14:41:13.214Z"
          description: The date and time when a processing of the notification is expected by the sender.
        messageId:
          type: string
          format: uuid
          example: "c2801472-5f87-41a7-9a25-b0939c4e0dff"
          description: A UUIDv4 to uniquely identify an individual quality notification message. In case of an initial sending of a notification the messageId has to be a newly generated UUIDv4.
    QualityNotificationGetResponseHeader:
      type: object
      required:
        - notificationId
        - senderBPN
        - senderAddress
        - recipientBPN
        - severity
        - status
        - messageId
      properties:
        notificationId:
          type: string
          format: uuid
          example: "a7954026-3aff-4b6c-92bf-04671ef2fa46"
          description: A UUIDv4 to uniquely identify a quality notification.
        senderBPN:
          type: string
          example: "BPNL00000003BW3S"
          description: The business partner number (BPN) of the sender.
        senderAddress:
          type: string
          format: uri
          example: "https://edc.company-xyz.io/BPNL00000003BW3S"
          description: The Eclipse Dataspace Connector (EDC) URL of the sender.
        recipientBPN:
          type: string
          example: "BPNL00000003BV4H"
          description: The business partner number (BPN) of the receiver.
        severity:
          $ref: '#/components/schemas/QualitySeverity'
        status:
          $ref: '#/components/schemas/QualityStatus'
        targetDate:
          type: string
          format: date-time
          example: "2022-07-28T14:41:13.214Z"
          description: The date and time when a processing of the notification is expected by the sender.
        messageId:
          type: string
          format: uuid
          example: "c2801472-5f87-41a7-9a25-b0939c4e0dff"
          description: A UUIDv4 to uniquely identify an individual quality notification message.
    QualityNotificationUpdateRequestHeader:
      type: object
      required:
         - notificationId
         - senderBPN
         - senderAddress
         - recipientBPN
         - status
         - messageId
      properties:
        notificationId:
          type: string
          format: uuid
          example: "a7954026-3aff-4b6c-92bf-04671ef2fa46"
          description: A UUIDv4 to uniquely identify a quality notification. Actually, this value cannot be updated. Rather, it is used to do a plausibility check.
        senderBPN:
          type: string
          example: "BPNL00000003BW3S"
          description: The business partner number (BPN) of the sender. Actually, this value cannot be updated. Rather, it is used to do a plausibility check.
        senderAddress:
          type: string
          format: uri
          example: "https://edc.company-xyz.io/BPNL00000003BW3S"
          description: The Eclipse Dataspace Connector (EDC) URL of the sender. Actually, this value cannot be updated. Rather, it is used to do a plausibility check.
        recipientBPN:
          type: string
          example: "BPNL00000003BV4H"
          description: The business partner number (BPN) of the receiver. Actually, this value cannot be updated. Rather, it is used to do a plausibility check.
        severity:
          $ref: '#/components/schemas/QualitySeverity'
        status:
          $ref: '#/components/schemas/QualityStatus'
        targetDate:
          type: string
          format: date-time
          example: "2022-07-28T14:41:13.214Z"
          description: The date and time when a processing of the notification is expected by the sender.
        messageId:
          type: string
          format: uuid
          example: "c2801472-5f87-41a7-9a25-b0939c4e0dff"
          description: A UUIDv4 to uniquely identify an individual quality notification message. In case of an update of a notification the messageId must be a newly generated UUIDv4. It must not be an existing messageId.
    QualityNotificationGetRequestHeader:
      type: object
      required:
         - notificationId
         - senderBPN
         - senderAddress
         - recipientBPN
      properties:
        notificationId:
          type: string
          format: uuid
          example: "a7954026-3aff-4b6c-92bf-04671ef2fa46"
          description: A UUIDv4 to uniquely identify a quality notification.
        senderBPN:
          type: string
          example: "BPNL00000003BW3S"
          description: The business partner number (BPN) of the sender. Actually, this value is not used to resolve the quality notification. Rather, it is used to do a plausibility check.
        senderAddress:
          type: string
          format: uri
          example: "https://edc.company-xyz.io/BPNL00000003BW3S"
          description: The Eclipse Dataspace Connector (EDC) URL of the sender. Actually, this value is not used to resolve the quality notification. Rather, it is used to do a plausibility check.
        recipientBPN:
          type: string
          example: "BPNL00000003BV4H"
          description: The business partner number (BPN) of the receiver. Actually, this value is not used to resolve the quality notification. Rather, it is used to do a plausibility check.
        messageId:
          type: string
          format: uuid
          example: "c2801472-5f87-41a7-9a25-b0939c4e0dff"
          description: A UUIDv4 to uniquely identify an individual quality notification message. If this parameter is provided, the message for this messageId is resolved. If this parameter is not provided, then the last available message is resolved.
    QualityNotificationReceivePayload:
      type: object
      required:
         - listOfAffectedItems
      properties:
        information:
          type: string
          maxLength: 1000
          example: "Gear boxes loose oil while driving."
        listOfAffectedItems:
          type: array
          items:
            type: string
          example:
            - "urn:uuid:57e4e3c1-a6f0-46a0-90df-1fb17cbc157d"
            - "urn:uuid:e4da568b-8cf1-4f5f-a96a-cf26265b2c72"
    QualityNotificationUpdatePayload:
      type: object
      properties:
        information:
          type: string
          maxLength: 1000
          example: "Gear boxes loose oil while driving."
    QualityNotificationReceiveRequestBody:
      required:
      - header
      - content
      type: object
      properties:
        header:
          $ref: '#/components/schemas/QualityNotificationReceiveRequestHeader'
        content:
          $ref: '#/components/schemas/QualityNotificationReceivePayload'
    QualityNotificationUpdateRequestBody:
      required:
      - header
      type: object
      properties:
        header:
          $ref: '#/components/schemas/QualityNotificationUpdateRequestHeader'
        content:
          $ref: '#/components/schemas/QualityNotificationUpdatePayload'          
    QualityClassification:
      type: string
      enum:
        - QM-Investigation
        - QM-Alert
      example: QM-Investigation
      description: The classification defines the type of quality notification.
    QualitySeverity:
      type: string
      enum:
        - MINOR
        - MAJOR
        - CRITICAL
        - LIFE-THREATENING
      example: CRITICAL
      description: The severity of the quality notification describes its criticality.
    QualityStatus:
      type: string
      enum:
        - CREATED
        - SENT
        - RECEIVED
        - ACKNOWLEDGED
        - ACCEPTED
        - DECLINED
        - CLOSED
      example: SENT
      description: The status of the quality notification.
