name: KIT-Promotion-Incubating
description: Request to promote your KIT
title: "[Promote KIT To Incubating]: "
labels: ["kit-promotion"]
assignees:
  - octocat
body:
  - type: input
    id: kit_name
    attributes:
      label: Name of the KIT
      description: The name of your KIT
    validations:
      required: true
  - type: input
    id: kit_repo
    attributes:
      label: KIT Repo
      description: Link to your KIT-Repo
    validations:
      required: true
  - type: checkboxes
    id: artefacts_and_Deliverables
    attributes:
      label: "Artefacts & Deliverables"
      description: "Tick the provided artefacts and deliverables"
      options:
        - label: Vision/Mission
        - label: Business Value(s)
        - label: Use Case/ Domain Explanation
        - label: Development Roadmap
        - label: Whitepaper
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: comments
      description: "Leave a comment or additional information!"

  