openapi: 3.1.0
info:
  version: 1.0.0
  title: SIS EDC Consumer
  license:
    name: MIT
servers:
  - url: http://example.mp.org
paths:
  /ProvideProductionForecastInformation:
    post:
      summary: Information provided by MP to Client
      operationId: ProvideProductionForecastInformation
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvideProductionForecastSchema'
      responses:
        '200':
          $ref: "#/components/responses/200"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '420':
          description: lowerAccuracyOfPrecision. the returned data has a lower precision than requested
        '421':
          description: noForecastAvailable. No data available
components:
  responses:
    '200':
      description: OK. The request has succeeded
    '201':
      description: OK, Precision not possible. The request has succeeded. Precision is not possible, the default precision will be used
    '400':
      description: 	Bad request. The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). 
    '401':
      description: 	Unauthorized. Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
    '403':
      description: Forbidden. The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. 
    '420':
      description: Unknown BPNS. The BPNS which is given as parameter is not registered in the data provider database as a direct partner. 
    '421':
      description: 	Invalid CustomerId. The customerID unknown or invalid 
    '422':
      description: 	Invalid OrderId.	The orderID not found or invalid
    '423':
      description: Invalid Notification Interval. The data field Notification interval is not set with a proper value or missing
    '424':
      description: Invalid Deviation. The data field Deviation is not set with a proper value or missing 
    '425':
      description: 	Forbidden. The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource.  
    '426':
      description: 	incomplete Request 
  schemas:
    ProvideProductionForecastSchema:
      description: Answer to a customer with all information about the requested items
      type: object
      properties:
        productionForecastResponse:
          description: The concrete information about a production forecast
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ProductionForecastCharacteristic'
        header:
          description: Contains information common to all messages
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_HeaderCharacteristic'
      required:
        - productionForecastResponse
        - header
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum:
      type: string
      pattern: '[a-zA-Z]*:[a-zA-Z]+'
      description: Enumerates all time units
      enum:
        - unit:secondUnitOfTime
        - unit:minuteUnitOfTime
        - unit:hour
        - unit:day
        - unit:week
        - unit:month
        - unit:year
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic:
      type: number
      description: The value of the specified timeUnit as an integer value
    urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum'
        value:
          description: The amount of timeUnits considered
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic'
      required:
        - timeUnit
        - value
    urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic:
      type: string
      description: Characteristic for defining BPN values
    urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    urn_samm_io.catenax.message_header_1.0.0_UuidCharacteristic:
      type: string
      description: Structured Value for defining a property which requires an UUID
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum:
      type: string
      description: Enumerates all possible communication modes
      enum:
        - synchronous
        - cyclic
        - notification
    urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_RequestCharacteristic:
      description: Data type for a request
      type: object
      properties:
        offset:
          description: |-
            Send/start time of the first message/notification
            - "0" ==> immediate response
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_TimeValueCharacteristic'
        customerId:
          description: Internal customerId
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic'
        precisionOfForecast:
          description: |-
            Accuracy of the time specification of the completion date.
            - default: implicitly defined by production
            - only as a REQUEST of the requester since it cannot be guaranteed that the store floor can provide the data in this accuracy.
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_TimeValueCharacteristic'
        productionForecastForAll:
          description: Boolean variable that detemines whether the customer request information about each position of an order, or information about the complete order
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Boolean'
        orderId:
          description: The Id identifying subject of the request
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_UuidCharacteristic'
        deviationOfSchedule:
          description: |-
            Mandatory property for the notification mode. The property specifies the deviation from targeted delivery date that must be met to send a notification to a subscriber

            mandatory for CommunicationMode = "notification"
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_TimeValueCharacteristic'
        notificationInterval:
          description: |-
            Interval time that either specifies the cyclic send time or limits the notification time
            mandatory for CommunicationMode = "cyclic"
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_request_1.0.0_TimeValueCharacteristic'
        communicationMode:
          description: Specification of the communication mode
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum'
        versionDataModel:
          description: Specifies the used version of the data model
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic'
      required:
        - offset
        - customerId
        - productionForecastForAll
        - orderId
        - communicationMode
        - versionDataModel
    urn_samm_io.catenax.message_header_1.0.0_ContextCharacteristic:
      type: string
      description: Defining a string value for the context
    urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Timestamp:
      type: string
      pattern: '-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?|(24:00:00(\.0+)?))(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
      description: Describes a Property which contains the date and time with an optional timezone.
    urn_samm_io.catenax.message_header_1.0.0_VersionCharacteristic:
      type: string
      description: Characteristic defining the value of version.
    urn_samm_io.catenax.message_header_1.0.0_HeaderCharacteristic:
      description: Characteristic describing the common shared aspect Message Header
      type: object
      properties:
        messageId:
          description: Unique ID identifying the message. The purpose of the ID is to uniquely identify a single message, therefore it MUST not be reused.
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_UuidCharacteristic'
        context:
          description: "Information about the context the message should be considered in.\r\nDefault: For Use Cases which need to validate against the Semantic Hub automatically.\r\nFallback: For Use Cases which do not use automatic validation.\r\nIn both cases: Versioning only refers to major versions.\r\nString pattern of the value follows: <domain>-<subdomain>-<object>-<major version>"
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_ContextCharacteristic'
        sentDateTime:
          description: Time zone aware timestamp holding the date and the time the message was sent by the sending party. The value MUST be formatted according to the ISO 8601 standard
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Timestamp'
        senderBpn:
          description: The Business Partner Number of the sending party. The value MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints are defined in the corresponding standard
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic'
        receiverBpn:
          description: The Business Partner Number of the receiving party. The value MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints are defined in the corresponding standard.
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic'
        expectedResponseBy:
          description: Time zone aware timestamp holding the date and time by which the sending party expects a certain type of response from the receiving party. The meaning and interpretation of the fields's value are context-bound and MUST therefore be defined by any business domain or platform capability making use of it. The value MUST be formatted according to the ISO 8601 standard
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Timestamp'
        relatedMessageId:
          description: Unique ID identifying a message somehow related to the current one
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_UuidCharacteristic'
        version:
          description: The version of the standard defining the semantics and the structure of the message's header. The version number should follow the Semantic Versioning 2.0.0 specification.
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_VersionCharacteristic'
      required:
        - messageId
        - context
        - sentDateTime
        - senderBpn
        - receiverBpn
        - version

    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum'
        value:
          description: The amount of timeUnits considered
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic'
      required:
        - timeUnit
        - value
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ProductionStatusEnum:
      type: string
      description: Enumeration with all possible states of an order within MP
      enum:
        - itemReceived
        - itemPlanned
        - itemInProduction
        - itemCompleted
        - statusUndefined
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ReasonsForDelayEnum:
      type: string
      description: Enum that specifies reasons for a delay of an order
      enum:
        - supplyProblems
        - otherCircumstances
        - internalProblems
        - noInformationAvailable
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ReturnCodeEnum:
      type: string
      description: Enumeration with all Return Codes
      enum:
        - ok
        - lowerAccuracyOfPrecision
        - noForecastAvailable
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ForecastItem:
      description: ForecastItem entry for the requested order
      type: object
      properties:
        positionId:
          description: Identifier of a position of an order
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_UuidCharacteristic'
        productionForecast:
          description: Date of completion
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Timestamp'
        precisionOfForecast:
          description: Accuracy of the prediction
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeValueCharacteristic'
        productionStatus:
          description: Status of the order/position within MP
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ProductionStatusEnum'
        reasonsForDelay:
          description: Optional field to provide information to the customer why a delivery date is not met
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ReasonsForDelayEnum'
        returnCode:
          description: Return code that indicates whether a single item of an order matches the customers desired request
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ReturnCodeEnum'
        forecastDate:
          description: Date/time of the forecast calculation
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Timestamp'
      required:
        - positionId
        - productionForecast
        - precisionOfForecast
        - productionStatus
        - returnCode
        - forecastDate
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ForecastItemList:
      description: List with the forecast items
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ForecastItem'
    urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ProductionForecastCharacteristic:
      description: All Data that is related to a production forecast
      type: object
      properties:
        listOfForecastItems:
          description: List of ForecastItems matching the items to an order
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.production_forecast_response_1.0.0_ForecastItemList'
        iterationNumber:
          description: |-
            Only set in CommunicationMode == "notification/cyclic" to be able to check the order of the notifications. 

            Not required for communication mode = "synchronous"
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic'
        communicationMode:
          description: Specification of the communication mode
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum'
        versionDataModel:
          description: Specifies the used version of the data model
          $ref: '#/components/schemas/urn_samm_io.catenax.message_header_1.0.0_BpnCharacteristic'
      required:
        - listOfForecastItems
        - communicationMode
        - versionDataModel