@startuml "PCF Request with missing Twin or Submodel"

participant PCF_Client
participant Client_API_Wapper
participant Client_EDC
participant EDC_Discovery_Service
participant Company_EDC
participant Company_DTR
participant Company_API_Wapper
participant Company_PCF_App

group Request PCF value

group Technical user login (not shown in detail here)
end

!includesub EDCDiscoveryAnddDTRAccess.puml!EDCDiscovery
!includesub EDCDiscoveryAnddDTRAccess.puml!DTRDiscovery

group Lookup PCF Submodel of Material Twin
PCF_Client -> Client_EDC: Lookup Twin's Submodel\nin Companies DTR\n(via Company's EDC URL)
Client_EDC -> Company_EDC: Negotiate DTR access & lookup\nTwin's Submodel in Company's DTR\n(using AAS API and materialID)
note right
Lookup Twin ID for material:
GET https://someEDCProxURL/lookup/shells?assetIds=[{"key": "manufacturerPartId","value":"mat345"},{"key": "digitalTwinType","value": "PartType"}]

Lookup Twin for ID
GET https://someEDCProxURL/registry/shell-descriptors/urn:uuid:c34018ab-5820-4065-9087-416d78e1ab60

end note
Company_EDC -> Company_DTR: Lookup Material Twin\nincl. PCF submodel
Company_DTR -> Company_EDC: Not Found!
Company_EDC -> Client_EDC: Not Found!
Client_EDC -> PCF_Client: Not Found!
end

!includesub PCFRequestAlternatives.puml!GetAssetViaType
group Send Request via EDC Proxying
PCF_Client -> Client_API_Wapper: Invoke asset with reqID & comment
note right

GET https://clientApiWrapperUrl/api/service/c34018ab-5820-4065-9087-416d78e1ab60/footprintExchange/123?manufacturerPartId=mat345&message=...
end note
Client_API_Wapper -> Client_EDC: Negotiate access to asset and enable proxy transfer
Client_EDC -> Company_EDC: Negotiate access to asset and enable proxy transfer
Company_EDC -> Client_EDC: Agreement & EndpointDataReference
Client_EDC -> Client_API_Wapper: Agreement & EndpointDataReference
Client_API_Wapper -> Client_EDC: PCF endpoint call incl. req.ID & comment
Client_EDC -> Company_EDC: PCF endpoint call incl. req.ID & comment
note right
GET https://{someURL}/footprintExchange/123?manufacturerPartId=mat345&message=...
end note
Company_EDC -> Company_PCF_App: PCF endpoint call incl. req.ID, BPN (Header) & comment
note right
Can we use existing
PCF API directly?
If so: no AAS adapter 
would be needed!
end note
Company_PCF_App -> Company_EDC: Accepted
Company_EDC -> Client_EDC: Accepted
Client_EDC -> Client_API_Wapper: Accepted
Client_API_Wapper -> PCF_Client: Accepted
end
end

Company_PCF_App -> Company_PCF_App: Approve PCF Request and\ncalculate PCF if needed

group Receive/Send PCF value

group Technical user login (not shown in detail here)
end

group Lookup Clients's EDC
Company_PCF_App -> EDC_Discovery_Service: Lookup EDC URL (via BPN)
note right
POST https://portal-backend.some.demo.catena-x.net/api/administration/connectors/discovery
{
   [ <Client's BPN> ] 
}
end note
EDC_Discovery_Service -> Company_PCF_App: EDC URL
end

group Lookup Clients PCF Receive Asset
Company_PCF_App -> Company_EDC: Lookup Client's Receive Asset\n(via Company's EDC URL)
Company_EDC -> Client_EDC: Lookup Asset in Catalog\n(EDC asset type '{"@id":"cx-taxo:PcfExchange"}')
note right
There could be multiple EDC URLs, but
only one with a PCF Exchange Asset
end note
Client_EDC -> Company_EDC: PCF Asset
Company_EDC -> Company_PCF_App: PCF Asset ID
end

group Push PCF to Client
Company_PCF_App -> Company_API_Wapper: Invoke asset with reqID
note right
PUT https://clientApiWrapperUrl/api/service/20ac18ab-5820-4065-9087-416d78e155cd/footprintExchange/123?manufacturerPartId=mat345&message=...
Header: edc-bpn: <BPN>
Body: { ...PCF JSON... }
end note
Company_API_Wapper -> Company_EDC: Negotiate access to asset and enable proxy transfer
Company_EDC -> Client_EDC: Negotiate access to asset and enable proxy transfer
Client_EDC -> Company_EDC: Agreement & EndpointDataReference
Company_EDC -> Company_API_Wapper: Agreement & EndpointDataReference
Company_API_Wapper -> Company_EDC: PCF endpoint call incl. req.ID
Company_EDC -> Client_EDC: PCF endpoint call incl. req.ID
note right
PUT https://{someURL}/footprintExchange/123?manufacturerPartId=mat345&message=...
Header: edc-bpn: <BPN>
Body: { ...PCF JSON... }
end note
Client_EDC -> PCF_Client: PCF endpoint call incl. req.ID, BPN (Header)
PCF_Client -> Client_EDC: OK
Client_EDC -> Company_EDC: OK
Company_EDC -> Company_API_Wapper: OK
Company_API_Wapper -> Company_PCF_App: OK
end
end
 
@enduml
