---
openapi: 3.0.3
info:
  title: ID Based Request For Update
  version: v2
paths:
  /internal-dcm-application-request-for-update-post-endpoint:
    post:
      summary: Receive request for update information
      description: Endpoint of an internal application responsible for recieving request for update information from a Catena-X partner. This endpoint must be called via EDC Asset definition.
      requestBody:
        $ref: '#/components/requestBodies/IdBasedRequestForUpdate'
      tags:
      - IdBasedRequestForUpdate
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "422":
          description: Unprocessable Entity
        "503":
          description: Service Unavailable
components:
  schemas:
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.id_based_request_for_update_2.0.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.id_based_request_for_update_2.0.0_MaterialDemandEntity:
      description: Encapsulates the information that is necessary for an update request.
      type: object
      properties:
        materialDemandId:
          description: The Material Demand ID uniquely identifies the material demand
            the supplier requests an update for within the business relationship between
            the customer and its supplier.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        changedAt:
          description: "Point in time of the last update known to the requesting business\
            \ partner. If the requested entity has been changed more recently, the\
            \ requested party should resend the data. If the changedAt property is\
            \ not given, the latest entity should be send without precondition."
          $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_Timestamp'
      required:
      - materialDemandId
    urn_samm_io.catenax.id_based_request_for_update_2.0.0_MaterialDemandCharacteristic:
      description: A list of material demand UUIDs without duplicates an update is
        requested for.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_MaterialDemandEntity'
      uniqueItems: true
    urn_samm_io.catenax.id_based_request_for_update_2.0.0_WeekBasedCapacityGroupEntity:
      description: Encapsulates the information that is necessary for an update request.
      type: object
      properties:
        capacityGroupId:
          description: The Capacity Group ID uniquely identifies the capacity group
            the supplier requests an update for within the business relationship between
            the supplier and its customer.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        changedAt:
          description: "Point in time of the last update known to the requesting business\
            \ partner. If the requested entity has been changed more recently, the\
            \ requested party should resend the data. If the changedAt property is\
            \ not given, the latest entity should be send without precondition."
          $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_Timestamp'
      required:
      - capacityGroupId
    urn_samm_io.catenax.id_based_request_for_update_2.0.0_WeekBasedCapacityGroupCharacteristic:
      description: A list of capacity group UUIDs without duplicates an update is
        requested for.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_WeekBasedCapacityGroupEntity'
      uniqueItems: true
    IdBasedRequestForUpdate:
      description: |-
        The requirements for a request for update from another Catena-X Partner of a specific entity.
        If within the payload, no specific object type is defined (Payload empty), than an update of all objects within the sender reciever relation is requested).
      type: object
      properties:
        materialDemand:
          description: |-
            Material demands the supplier requests an update for.
            If within the array, no specific ID (array empty), than an update of all IDs is requested).
          $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_MaterialDemandCharacteristic'
        weekBasedCapacityGroup:
          description: |-
            Capacity groups the customer requests an update for.
            If within the array, no specific ID (array empty), than an update of all IDs is requested).
          $ref: '#/components/schemas/urn_samm_io.catenax.id_based_request_for_update_2.0.0_WeekBasedCapacityGroupCharacteristic'
  requestBodies:
    IdBasedRequestForUpdate:
      description: This request body defines the payload with it's mandatory and optional properties that must be sent to this endpoint.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdBasedRequestForUpdate'