---
openapi: 3.0.3
info:
  title: Material Demand
  version: v1
paths:
  /internal-dcm-application-material-demand-post-endpoint:
    post:
      summary: Receive material demand information
      description: Endpoint of an internal application responsible for receiving material demand information from a Catena-X partner. This endpoint must be called via EDC Asset definition.
      requestBody:
        $ref: '#/components/requestBodies/MaterialDemand'
      tags:
      - MaterialDemand
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "422":
          description: Unprocessable Entity
        "503":
          description: Service Unavailable
components:
  schemas:
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    DemandCategoryDefault:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - '0001'
      required:
      - demandCategoryCode
    DemandCategoryAfterSales:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - A1S1
      required:
      - demandCategoryCode
    DemandCategorySeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - SR99
      required:
      - demandCategoryCode
    DemandCategoryPhaseInPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PI01
      required:
      - demandCategoryCode
    DemandCategorySingleOrder:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OS01
      required:
      - demandCategoryCode
    DemandCategorySmallSeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OI01
      required:
      - demandCategoryCode
    DemandCategoryExtraordinaryDemand:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - ED01
      required:
      - demandCategoryCode
    DemandCategoryPhaseOutPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PO01
      required:
      - demandCategoryCode
    urn_samm_io.catenax.material_demand_1.0.0_DemandCategoryCharacteristic:
      description: The classification of demands used for prioritization or allocation.
      type: object
      oneOf:
      - $ref: '#/components/schemas/DemandCategoryDefault'
      - $ref: '#/components/schemas/DemandCategoryAfterSales'
      - $ref: '#/components/schemas/DemandCategorySeries'
      - $ref: '#/components/schemas/DemandCategoryPhaseInPeriod'
      - $ref: '#/components/schemas/DemandCategorySingleOrder'
      - $ref: '#/components/schemas/DemandCategorySmallSeries'
      - $ref: '#/components/schemas/DemandCategoryExtraordinaryDemand'
      - $ref: '#/components/schemas/DemandCategoryPhaseOutPeriod'
    urn_samm_io.catenax.material_demand_1.0.0_QuantityTrait:
      type: number
      description: "Constraint to ensure size of quantities: 12 digits plus 3 decimal\
        \ places."
      maximum: 999999999999999999.999
      exclusiveMaximum: false
      minimum: 0
      exclusiveMinimum: false
    urn_samm_io.catenax.material_demand_1.0.0_PointInTimeCharacteristic:
      type: string
      format: date
      description: |-
        - If demand rate is "calendar week": An ISO calendar week in which a given demand is needed. Must be given as date of the Monday in the week. (ISO-8601-1:2019)
        - If demand rate is "day": An ISO day on which a given demand is needed. Must be given as single day (consider the time zone of the customer's location). (ISO-8601)
    urn_samm_io.catenax.material_demand_1.0.0_Demand:
      description: A single demand for a given point in time according to the demand
        rate.
      type: object
      properties:
        demand:
          description: ' Quantity of materials required in the specified point in
            time according specified demand rate. This demand should be as close as
            possible to demand that is derived from the actual production program.'
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_QuantityTrait'
        pointInTime:
          description: Defines the start of the demand rate as a point in time. The
            point in time must be interpreted according to the demand rate.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_PointInTimeCharacteristic'
      required:
      - demand
      - pointInTime
    urn_samm_io.catenax.material_demand_1.0.0_DemandDateSeries:
      description: The demands in a given time period for a given demand rate.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_Demand'
      uniqueItems: true
    urn_samm_io.catenax.material_demand_1.0.0_DemandSeries:
      description: Encapsulates the demand series related information.
      type: object
      properties:
        customerLocation:
          description: The Business Partner Number Site (BPNS) of the site at which
            the customer needs the specified material for this demand series.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait'
        demandCategory:
          description: Type of demand for this demand series.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_DemandCategoryCharacteristic'
        demands:
          description: A time series with a specified demand rate along a given time
            period to describe the demand values for this demand series.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_DemandDateSeries'
        expectedSupplierLocation:
          description: The Business Partner Number Site (BPNS) of the site from where
            the customer expects the supplier to fulfill the demands of the demand
            series. The value is used for informational purposes only and is therefore
            not binding for the supplier.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait'
      required:
      - customerLocation
      - demandCategory
      - demands
    urn_samm_io.catenax.material_demand_1.0.0_DemandSeriesSet:
      description: A set of demand series belonging to a certain material demand.
        Each demand series in the set must have a unique combination of customer location
        and demand category.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_DemandSeries'
      uniqueItems: true
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait:
      type: string
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    urn_samm_io.catenax.material_demand_1.0.0_MaterialNumber:
      type: string
      description: "The material number is a multi-character string, usually assigned\
        \ by an ERP system."
    urn_samm_io.catenax.material_demand_1.0.0_MaterialDescription:
      type: string
      description: Description of a material demand.
    urn_samm_io.catenax.material_demand_1.0.0_Timestamp:
      type: string
      format: date-time
      description: Point in time.
    urn_samm_io.catenax.material_demand_1.0.0_MaterialGlobalAssetIdTrait:
      type: string
      description: "The provided regular expression ensures that the string starts\
        \ with urn:uuid: followed by the UUID which is composed of five groups of\
        \ characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36\
        \ characters (32 hexadecimal characters and 4 hyphens)."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    DemandRateCalendarWeek:
      type: object
      properties:
        demandRateCode:
          description: Code identifying the demand rate.
          type: string
          enum:
          - WKS
      required:
      - demandRateCode
    DemandRateDay:
      type: object
      properties:
        demandRateCode:
          description: Code identifying the demand rate.
          type: string
          enum:
          - DAY
      required:
      - demandRateCode
    urn_samm_io.catenax.material_demand_1.0.0_DemandRateEnumeration:
      description: |-
        The demand rate specifies the time horizon of the the demand.
        - day = time between the start of the specified day till the end of the specified day (ISO-8601).
        - calendar week = time between the start of the specified calendar week till the end of the specified calendar week (ISO-8601-1:2019).
      type: object
      oneOf:
      - $ref: '#/components/schemas/DemandRateCalendarWeek'
      - $ref: '#/components/schemas/DemandRateDay'
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    MaterialDemand:
      description: "The requirements of a customer towards a specific supplier for\
        \ a specific material. Each material demand is unique by its Customer, Supplier\
        \ and Material Number."
      type: object
      properties:
        materialDemandId:
          description: The Material Demand ID uniquely identifies the material demand
            within the business relationship between a customer and its supplier.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        demandSeries:
          description: "The demands for a dedicated material in a given time period\
            \ of a given demand rate, distinguished by their demand location and demand\
            \ category."
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_DemandSeriesSet'
        customer:
          description: The Business Partner Number Legal Entity (BPNL) of the party
            requesting materials from a supplier.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait'
        supplier:
          description: The Business Partner Number Legal Entity (BPNL) of the party
            providing materials to a customer.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait'
        unitOfMeasure:
          description: Unit of measurement for demand quantities.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration'
        materialNumberCustomer:
          description: Material identifier as assigned by customer. This material
            number identifies the material (as planned) in customer's database. Must
            be unique for each Material Demand in the customer-supplier relationship.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_MaterialNumber'
        materialNumberSupplier:
          description: Material identifier as assigned by supplier. This material
            number identifies the material (as planned) in supplier's database.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_MaterialNumber'
        materialDescriptionCustomer:
          description: Description of the material.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_MaterialDescription'
        changedAt:
          description: "Point in time when the content (any property according to\
            \ the data model) of the material demand was changed, at the customer,\
            \ either by a human user or an automated process."
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_Timestamp'
        materialGlobalAssetId:
          description: Material identifier used uniquely within Catena-X to identify
            the Material (e.g. PartAsPlanned).
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        demandRate:
          description: Describes the demand rate or granularity of the demand information.
            It defines how to interpret the point in time.
          $ref: '#/components/schemas/urn_samm_io.catenax.material_demand_1.0.0_DemandRateEnumeration'
        unitOfMeasureIsOmitted:
          description: Explicit indicator of whether the unit of measure is left out
            of the payload intentionally. If "true" it means the sending application
            sends demand values without unit of measure intentionally and the unit
            of measure MUST NOT be contained in the payload. If "false" a unit of
            measure MUST be supplied.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
      required:
      - materialDemandId
      - demandSeries
      - customer
      - supplier
      - materialNumberCustomer
      - materialDescriptionCustomer
      - changedAt
      - demandRate
      - unitOfMeasureIsOmitted
  requestBodies:
    MaterialDemand:
      description: This request body defines the payload with it's mandatory and optional properties that must be sent to this endpoint.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MaterialDemand'