---
openapi: 3.0.3
info:
  title: Week-Based Capacity Group
  version: v2
paths:
  /internal-dcm-application-capacity-group-post-endpoint:
    post:
      summary: Receive capacity group information
      description: Endpoint of an internal application responsible for recieving capacity group information from a Catena-X partner. This endpoint must be called via EDC Asset definition.
      requestBody:
        $ref: '#/components/requestBodies/WeekBasedCapacityGroup'
      tags:
      - WeekBasedCapacityGroup
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "422":
          description: Unprocessable Entity
        "503":
          description: Service Unavailable
components:
  schemas:
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_CapacityGroupName:
      type: string
      description: "The name of a capacity group, used to distinguish it from other\
        \ capacity groups."
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_SupplierLocationsCharacteristic:
      description: Contains a set of locations the supplier fulfills a demand request
        from.
      type: array
      items:
        type: string
        description: "The provided regular expression ensures that the BPNS is composed\
          \ of prefix 'BPNS', 10 digits and two uppercase letters."
        pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
      uniqueItems: true
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait:
      type: string
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_MaterialNumber:
      type: string
      description: "The material number is a multi-character string, usually assigned\
        \ by an ERP system."
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    DemandCategoryDefault:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - '0001'
      required:
      - demandCategoryCode
    DemandCategoryAfterSales:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - A1S1
      required:
      - demandCategoryCode
    DemandCategorySeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - SR99
      required:
      - demandCategoryCode
    DemandCategoryPhaseInPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PI01
      required:
      - demandCategoryCode
    DemandCategorySingleOrder:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OS01
      required:
      - demandCategoryCode
    DemandCategorySmallSeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OI01
      required:
      - demandCategoryCode
    DemandCategoryExtraordinaryDemand:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - ED01
      required:
      - demandCategoryCode
    DemandCategoryPhaseOutPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PO01
      required:
      - demandCategoryCode
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_DemandCategoryCharacteristic:
      description: The classification of demands used to prioritize or allocate capacities.
      type: object
      oneOf:
      - $ref: '#/components/schemas/DemandCategoryDefault'
      - $ref: '#/components/schemas/DemandCategoryAfterSales'
      - $ref: '#/components/schemas/DemandCategorySeries'
      - $ref: '#/components/schemas/DemandCategoryPhaseInPeriod'
      - $ref: '#/components/schemas/DemandCategorySingleOrder'
      - $ref: '#/components/schemas/DemandCategorySmallSeries'
      - $ref: '#/components/schemas/DemandCategoryExtraordinaryDemand'
      - $ref: '#/components/schemas/DemandCategoryPhaseOutPeriod'
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_LoadFactorCharacteristic:
      type: number
      description: Describes the data type of the load factor.
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedDemandSeries:
      description: Encapsulates information used to reference a specific demand series.
      type: object
      properties:
        materialNumberCustomer:
          description: Material identifier as assigned by customer. This material
            number identifies the material (as planned) in the customer's database.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_MaterialNumber'
        materialNumberSupplier:
          description: "Material identifier as assigned by supplier. This material\
            \ number identifies the material (as planned) in the supplier's database.\
            \ Used as informational field only, not for assigning demand series to\
            \ capacity groups."
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_MaterialNumber'
        customerLocation:
          description: The BPNS number of the site at which the customer needs the
            specified material for the referenced demand series.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait'
        demandCategory:
          description: Type of demand of the referenced demand series.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_DemandCategoryCharacteristic'
        loadFactor:
          description: "If existent, the load factor indicates that this material\
            \ of the material demand collection takes a factor more or less intensity\
            \ to produce."
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_LoadFactorCharacteristic'
      required:
      - materialNumberCustomer
      - customerLocation
      - demandCategory
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedDemandSeriesSet:
      description: A set of demand series assigned to a certain capacity group.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedDemandSeries'
      uniqueItems: true
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_PointInTimeCharacteristic:
      type: string
      format: date
      description: An ISO calendar week in which a given capacity will be provided.
        Must be given as date of the monday in the week.
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_QuantityTrait:
      type: number
      description: "Constraint to ensure size of quantities: 12 digits plus 3 decimal\
        \ places."
      maximum: 999999999999999999.999
      exclusiveMaximum: false
      minimum: 0
      exclusiveMinimum: false
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_DeltaProductionResultCharacteristic:
      type: number
      description: Describes data type of a delta production result information.
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_Capacity:
      description: "A supplier's realistically planned output per calendar week and\
        \ material for a specific customer in a specific unit of measure, considering\
        \ all positive or negative impacts on this capacity."
      type: object
      properties:
        pointInTime:
          description: ISO Calendar Week of the given time series entry. Must be given
            as date of the monday in the week.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_PointInTimeCharacteristic'
        actualCapacity:
          description: "The actual capacity is the realistically planned output per\
            \ calendar week and material for a specific customer in a specific unit\
            \ of measure, considering all positive or negative impacts on this capacity."
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_QuantityTrait'
        maximumCapacity:
          description: "The supplier maximum capacity is the maximal available output\
            \ per calendar week and material for a specific customer in a specific\
            \ unit of measure. The maximum capacity thereby restricts the flexible\
            \ capacity, as the flexible capacity is obtained from the difference of\
            \ a suppliers maximum capacity minus actual capacity."
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_QuantityTrait'
        deltaProductionResult:
          description: Delta related to the aggregated material demand after pre-/post
            production calculation the supplier wants to send to the customer. Can
            be positive and negative.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_DeltaProductionResultCharacteristic'
      required:
      - pointInTime
      - actualCapacity
      - maximumCapacity
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_CapacityTimeSeries:
      description: The weekly actual and maximum capacities in a given time period.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_Capacity'
      uniqueItems: true
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_Timestamp:
      type: string
      format: date-time
      description: Point in time.
    urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedCapacityGroupsCharacteristic:
      description: Contains all capacity groups which are linked to the current one.
      type: array
      items:
        type: string
        description: "The provided regular expression ensures that the UUID is composed\
          \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
          \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
          \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
        pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      uniqueItems: true
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    WeekBasedCapacityGroup:
      description: An entity made up of the weekly actual and maximum capacities for
        a specific customer in a given time period. A capacity group is used to compare
        demand and capacity data for one or several similar bundled materials in a
        defined unit of measure.
      type: object
      properties:
        capacityGroupId:
          description: The Capacity Group ID uniquely identifies the capacity group
            within the business relationship between a supplier and its customer.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        name:
          description: Name of the capacity group.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_CapacityGroupName'
        supplierLocations:
          description: Set of BPNS indicating the supplier sites that will be fulfilling
            the demands associated with this capacity group.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_SupplierLocationsCharacteristic'
        customer:
          description: The Business Partner Number (BPNL) of the party requesting
            materials from a supplier.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait'
        supplier:
          description: The Business Partner Number (BPNL) of the party providing materials
            to a customer.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait'
        unitOfMeasure:
          description: Unit of measurement for capacity quantities.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration'
        linkedDemandSeries:
          description: Set of demand series assigned to this capacity group.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedDemandSeriesSet'
        capacities:
          description: A time series with week-based granularity along a given time
            period containing the capacity values.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_CapacityTimeSeries'
        changedAt:
          description: "Point in time when the content (any property according to\
            \ the data model) of the capacity group was changed, at the supplier,\
            \ either by a human user or an automated process."
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_Timestamp'
        linkedCapacityGroups:
          description: A set of capacity groups linked to this capacity group.
          $ref: '#/components/schemas/urn_samm_io.catenax.week_based_capacity_group_2.0.0_LinkedCapacityGroupsCharacteristic'
        unitOfMeasureIsOmitted:
          description: Explicit indicator of whether the unit of measure is left out
            of the payload intentionally. If "true" it means the sending application
            sends demand values without unit of measure intentionally and the unit
            of measure MUST NOT be contained in the payload. If "false" a unit of
            measure MUST be supplied.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
      required:
      - capacityGroupId
      - name
      - customer
      - supplier
      - changedAt
      - unitOfMeasureIsOmitted
  requestBodies:
    WeekBasedCapacityGroup:
      description: This request body defines the payload with it's mandatory and optional properties that must be sent to this endpoint.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WeekBasedCapacityGroup'