openapi: 3.0.1
paths:
  /instances:
    get:
      operationId: getAll
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/DataPlaneInstance'
          description: default response
      tags:
      - Dataplane Selector
    post:
      operationId: addEntry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataPlaneInstance'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - Dataplane Selector
  /instances/select:
    post:
      operationId: find
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionRequest'
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPlaneInstance'
          description: default response
      tags:
      - Dataplane Selector
components:
  schemas:
    DataAddress:
      type: object
      example: null
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
    DataPlaneInstance:
      type: object
      example: null
      properties:
        allowedDestTypes:
          type: array
          example: null
          items:
            type: string
            example: null
          uniqueItems: true
        allowedSourceTypes:
          type: array
          example: null
          items:
            type: string
            example: null
          uniqueItems: true
        id:
          type: string
          example: null
        lastActive:
          type: integer
          format: int64
          example: null
        properties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        turnCount:
          type: integer
          format: int32
          example: null
        url:
          type: string
          format: url
          example: null
    SelectionRequest:
      type: object
      example: null
      properties:
        destination:
          $ref: '#/components/schemas/DataAddress'
        source:
          $ref: '#/components/schemas/DataAddress'
        strategy:
          type: string
          example: null
