openapi: 3.0.1
paths:
  /callback/{processId}/deprovision:
    post:
      operationId: callDeprovisionWebhook
      parameters:
      - in: path
        name: processId
        required: true
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeprovisionedResource'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - HTTP Provisioner Webhook
  /callback/{processId}/provision:
    post:
      operationId: callProvisionWebhook
      parameters:
      - in: path
        name: processId
        required: true
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionerWebhookRequest'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - HTTP Provisioner Webhook
components:
  schemas:
    DataAddress:
      type: object
      example: null
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
    DeprovisionedResource:
      type: object
      example: null
      properties:
        error:
          type: boolean
          example: null
        errorMessage:
          type: string
          example: null
        inProcess:
          type: boolean
          example: null
        provisionedResourceId:
          type: string
          example: null
    ProvisionerWebhookRequest:
      type: object
      example: null
      properties:
        apiKeyJwt:
          type: string
          example: null
        assetId:
          type: string
          example: null
        contentDataAddress:
          $ref: '#/components/schemas/DataAddress'
        hasToken:
          type: boolean
          example: null
        resourceDefinitionId:
          type: string
          example: null
        resourceName:
          type: string
          example: null
      required:
      - apiKeyJwt
      - assetId
      - contentDataAddress
      - resourceDefinitionId
      - resourceName
