openapi: 3.0.1
info:
  title: tx-edc-extensions-api
  description: Tractus X Extensions REST API Doc
  version: 0.5.0-SNAPSHOT
servers:
- url: /
paths:
  /aas/request:
    post:
      tags:
      - Data Plane Proxy API
      operationId: requestAsset
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AssetRequest'
      responses:
        default:
          description: Requests asset data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetRequest'
  /adapter/edrs:
    get:
      tags:
      - Control Plane Adapter EDR Api
      description: Returns all EndpointDataReference entry according to a query
      operationId: queryEdrs
      parameters:
      - name: assetId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: null
      - name: agreementId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/EndpointDataReferenceEntry'
        "400":
          description: Request was malformed
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
    post:
      tags:
      - Control Plane Adapter EDR Api
      description: Initiates an EDR negotiation by handling a contract negotiation
        first and then a transfer process for a given offer and with the given counter
        part. Please note that successfully invoking this endpoint only means that
        the negotiation was initiated.
      operationId: initiateEdrNegotiation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  example: null
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
              additionalProperties:
                $ref: '#/components/schemas/NegotiateEdrRequestDto'
              example: null
      responses:
        "200":
          description: The negotiation was successfully initiated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdResponseDto'
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
  /adapter/edrs/{id}:
    get:
      tags:
      - Control Plane Adapter EDR Api
      description: Gets an EDR  with the given transfer process ID)
      operationId: getEdr
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: null
      responses:
        "200":
          description: The EDR cached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAddressDto'
        "400":
          description: "Request was malformed, e.g. id was null"
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
        "404":
          description: An EDR with the given ID does not exist
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
  /gateway/{paths}:
    get:
      tags:
      - Data Plane Proxy API
      operationId: requestAsset
      responses:
        default:
          description: Gets asset data
          content:
            application/json: {}
components:
  schemas:
    Action:
      type: object
      properties:
        constraint:
          $ref: '#/components/schemas/Constraint'
        includedIn:
          type: string
          example: null
        type:
          type: string
          example: null
      example: null
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
          example: null
        message:
          type: string
          example: null
        path:
          type: string
          example: null
        type:
          type: string
          example: null
      example: null
    AssetRequest:
      type: object
      properties:
        assetId:
          type: string
          example: null
        endpointUrl:
          type: string
          example: null
        transferProcessId:
          type: string
          example: null
      example: null
    CallbackAddress:
      type: object
      properties:
        authCodeId:
          type: string
          example: null
        authKey:
          type: string
          example: null
        events:
          uniqueItems: true
          type: array
          example: null
          items:
            type: string
            example: null
        transactional:
          type: boolean
          example: null
        uri:
          type: string
          example: null
      example: null
    Constraint:
      required:
      - edctype
      type: object
      properties:
        edctype:
          type: string
          example: null
      example: null
      discriminator:
        propertyName: edctype
    ContractOfferDescription:
      type: object
      properties:
        assetId:
          type: string
          example: null
        offerId:
          type: string
          example: null
        policy:
          $ref: '#/components/schemas/Policy'
      example: null
    DataAddressDto:
      required:
      - properties
      type: object
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
      example: null
    Duty:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        consequence:
          $ref: '#/components/schemas/Duty'
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        target:
          type: string
          example: null
      example: null
    EndpointDataReferenceEntry:
      type: object
      properties:
        agreementId:
          type: string
          example: null
        assetId:
          type: string
          example: null
        transferProcessId:
          type: string
          example: null
      example: null
    IdResponseDto:
      type: object
      properties:
        '@context':
          type: object
          example: null
        '@id':
          type: string
          example: null
        '@type':
          type: string
          example: null
        createdAt:
          type: integer
          format: int64
          example: null
      example: null
    JsonObject:
      type: object
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          example: null
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      additionalProperties:
        $ref: '#/components/schemas/JsonValue'
      example: null
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          example: null
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      example: null
    NegotiateEdrRequestDto:
      required:
      - connectorAddress
      - connectorId
      - offer
      - protocol
      type: object
      properties:
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddress'
        connectorAddress:
          type: string
          example: null
        connectorId:
          type: string
          example: null
        offer:
          $ref: '#/components/schemas/ContractOfferDescription'
        protocol:
          type: string
          example: null
        providerId:
          type: string
          example: null
      example: null
    Permission:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        target:
          type: string
          example: null
      example: null
    Policy:
      type: object
      properties:
        '@type':
          type: string
          example: null
          enum:
          - SET
          - OFFER
          - CONTRACT
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        inheritsFrom:
          type: string
          example: null
        obligations:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        permissions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Prohibition'
        target:
          type: string
          example: null
      example: null
    Prohibition:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        target:
          type: string
          example: null
      example: null
