---
openapi: 3.0.1
info:
  title: OSim API
  description: OSim API for requesting and receiving simulation results
  version: 1.0.0
servers:
- url: "https://{server-url}"
tags:
- name: requestLatestSimulationResult
  description: Request Latest Simulation Result
- name: receiveLatestSimulationResult
  description: Receive Latest Simulation Result
paths:
  /api/requestLatestSimulationResult/bpns/{bpns}/requestId/{requestId}/simulationRunId/{simulationRunId}:
    get:
      tags:
      - requestLatestSimulationResult
      description: Request latest simulation result by referring the latest simulation run id available in own OSim Manager
      operationId: requestLatestSimulationResult
      parameters:
      - name: requestId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 8d628899-3e6f-4666-91c3-74ee7ab88b2b
      - name: bpns
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: bbf461bf-28d5-4fc2-95fa-7697eb122f48
      - name: simulationRunId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 50737df3-4237-4652-b092-1ef8649f6ca6
      responses:
        "200":
          description: Request Received
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
      - url: "https://{server-url}"
    servers:
    - url: "https://{server-url}"
  /api/receiveLatestSimulationResult/requestId/{requestId}:
    post:
      tags:
      - receiveLatestSimulationResult
      description: Receive latest simulation result which can be stored in own OSim Manager instance
      operationId: receiveLatestSimulationResult
      parameters:
      - name: requestId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 8d628899-3e6f-4666-91c3-74ee7ab88b2b
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestId_requestId_body'
            examples:
              "0":
                value: "{ \n  \"owner\": { \"id\": \"BPNL00000007OTZ3\" }, \n  \"dataQuality\": 1, \n  \"description\": \"Daily standard simulation\", \n  \"comment\": \"successful simulation\", \n  \"expirationTimestamp\": \"2023-03-24T09:15:24.000Z\", \n  \"runId\": \"0fece48b-c8d1-4180-1a9caca6d67e\", \n  \"shipments\": [ \n    { \n      \"handlingUnits\": [ \n       { \n          \"name\": \"Palette\", \n          \"volume\": 1, \n          \"weight\": 189, \n          \"batches\": [ \n            { \n              \"unitOfMeasurement\": \"KG\", \n              \"materialName\": \"KK1000GR-Gehäuse-Rot\", \n              \"quantity\": 50, \n              \"materialNumber\": \"KK1000GR\", \n              \"batchOrderId\": \"Order-0001\", \n              \"batchId\": \"Batch_1\", \n              \"hazardousGoods\": false, \n              \"batchExpirationTimestamp\": \"2023-08-22T16:00:00.000Z\", \n              \"batchNumber\": \"45\" \n            } \n          ], \n          \"handlingUnitId\": \"HUT_1\", \n          \"amount\": 1 \n        } \n      ], \n      \"shipmentId\": \"DE51515151\", \n      \"recipientTimestampPlanned\": \"2023-04-19T09:00:00.000Z\", \n      \"destination\": { \"id\": \"BPNL00000007OTZ3\" }, \n      \"recipient\": { \"id\": \"BPNL00000007OTZ4\" }, \n      \"logistics\": { \"id\": \"BPNL00000007OS0H\" }, \n      \"preceding\": {}, \n      \"splittingAllowed\": true, \n      \"destinationTimestamp\": \"2023-03-19T09:00:00.000Z\" \n    } \n  ], \n  \"timestamp\": \"2023-03-09T14:13:42.806Z\" \n}"
      responses:
        "200":
          description: Simulation Result Received
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
      - url: "https://{server-url}"
    servers:
    - url: "https://{server-url}"
components:
  schemas:
    apireceiveLatestSimulationResultrequestIdrequestId_owner:
      type: object
      properties:
        id:
          type: string
    apireceiveLatestSimulationResultrequestIdrequestId_handlingUnits:
      type: object
      properties:
        volume:
          type: integer
        batches:
          type: array
          items:
            $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_batches'
        handlingUnitId:
          type: string
        amount:
          type: integer
        name:
          type: string
        weight:
          type: integer
    apireceiveLatestSimulationResultrequestIdrequestId_batches:
      type: object
      properties:
        unitOfMeasurement:
          type: string
        materialName:
          type: string
        quantity:
          type: integer
        materialNumber:
          type: string
        batchOrderId:
          type: string
        batchId:
          type: string
        hazardousGoods:
          type: boolean
        batchExpirationTimestamp:
          type: string
        batchNumber:
          type: string
    requestId_requestId_body:
      type: object
      properties:
        owner:
          $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_owner'
        dataQuality:
          type: integer
        description:
          type: string
        comment:
          type: string
        expirationTimestamp:
          type: string
        runId:
          type: string
        shipments:
          type: array
          items:
            $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_shipments'
        timestamp:
          type: string
    apireceiveLatestSimulationResultrequestIdrequestId_shipments:
      type: object
      properties:
        handlingUnits:
          type: array
          items:
            $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_handlingUnits'
        shipmentId:
          type: string
        recipientTimestampPlanned:
          type: string
        destination:
          $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_owner'
        recipient:
          $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_owner'
        logistics:
          $ref: '#/components/schemas/apireceiveLatestSimulationResultrequestIdrequestId_owner'
        preceding:
          type: object
          properties: {}
        splittingAllowed:
          type: boolean
        destinationTimestamp:
          type: string
