openapi: 3.0.1
info:
  title: EDC Control Plane Adapter API
  description:
  license:
    name: Apache License v2.0
    url: http://apache.org/v2
  version: 0.0.1-SNAPSHOT
paths:
  /adapter/asset/sync/{assetId}:
    get:
      operationId: getAssetSynchronous
      parameters:
      - in: path
        name: assetId
        required: true
        schema:
          type: string
          example: null
      - in: query
        name: providerUrl
        schema:
          type: string
          example: null
      - in: query
        name: contractAgreementId
        schema:
          type: string
          example: null
      - in: query
        name: contractAgreementReuse
        schema:
          type: boolean
          default: true
          example: null
      - in: query
        name: timeout
        schema:
          type: string
          example: null
      responses:
        default:
          description: default response
      tags:
      - Control Plane Adapter
