openapi: 3.0.1
info:
  title: Unique ID Push Notification API
  description: API documentation for Traceability Unique ID Push Notifications
  license:
    name: Apache License v2.0
    url: http://apache.org/v2
  version: 1.0.0
servers:
- url: /
tags:
- name: Catena-X Traceability Unique ID Push Notification
  description: 'API to receive Unique ID push notifications for Catena-X Traceability.'
paths:
  /uniqueidpush/receive:
    post:
      tags:
      - Unique ID Push Notification
      description: Receives a Traceability Unique Id push notification
      operationId: receiveUniqueIdPushNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniqueIdPushNotificationReceiveRequestBody'
      responses:
        "201":
          description: Notification was received successfully
        "400":
          description: Request body was malformed
        "401":
          description: Not authorized     
        "403":
          description: Forbidden
        "405":
          description: Method not allowed
        "409":
          description: Could not accept the send notification, because a notification with that notificationId already exists
        "422":
          description: Could not accept the send notification even though it is syntactically correct. The notification is not accepted, because of semantic reasons (e.g., an item is not known by the receiver).
components:
  schemas:
    UniqueIdPushNotificationReceiveRequestBody:
      required:
      - header
      - content
      type: object
      properties:
        header:
          $ref: '#/components/schemas/UniqueIdPushNotificationReceiveRequestHeader'
        content:
          $ref: '#/components/schemas/UniqueIdPushNotificationReceivePayload'
    UniqueIdPushNotificationReceiveRequestHeader:
      type: object
      required:
        - notificationId
        - senderBPN
        - senderAddress
        - recipientBPN
        - classification
      properties:
        notificationId:
          type: string
          format: uuid
          example: "a7954026-3aff-4b6c-92bf-04671ef2fa46"
          description: A UUIDv4 to uniquely identify a Unique ID push notification.
        senderBPN:
          type: string
          example: "BPNL00000003BW3S"
          description: The business partner number (BPN) of the sender.
        senderAddress:
          type: string
          format: uri
          example: "https://edc.company-xyz.io/BPNL00000003BW3S"
          description: The Eclipse Dataspace Connector (EDC) URL of the sender.
        recipientBPN:
          type: string
          example: "BPNL00000003BV4H"
          description: The business partner number (BPN) of the receiver.
        classification:
          $ref: '#/components/schemas/UniqueIdPushClassification'
    UniqueIdPushNotificationReceivePayload:
      type: object
      required:
         - listOfItems
      properties:
        information:
          type: string
          maxLength: 1000
          example: "Update of serialized parts and batches for which digital twins were created."
        listOfItems:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/SerializedPartItem'
              - $ref: '#/components/schemas/BatchItem'
    UniqueIdPushClassification:
      type: string
      enum:
        - Child-Relationship
      example: Child-Relationship
      description: The classification defines the type of the Unique ID push notification.
    SerializedPartItem:
      type: object
      required:
        - manufacturerId
        - manufacturerPartId
        - partInstanceId
        - catenaxId
      properties:
        manufacturerId:
          type: string
          example: "BPNL00000003BW3S"
          description: The Business Partner Number (BPNL) of the manufacturer of the serialized part, i.e., the companies main entry.
        manufacturerPartId:
          type: string
          example: "8840838-04"
          description: The ID of the type/catalog part (of which the serialized part is an instance of) from the manufacturer.
        customerPartId:
          type: string
          example: "AAX178378"
          description: The ID of the type/catalog part (of which the serialized part is an instance of) from the customer.
        partInstanceId:
          type: string
          example: "NO-009284492099792129568369"
          description: The serial number of the serialized part from the manufacturer. We assume here that the customer does not have or create its own serial number for a part, but just used the manufacturer's serial number.
        catenaxId:
          type: string
          example: "urn:uuid:d32d3b55-d222-41e9-8d19-554af53124dd"
          description: Catena-X ID for a serialized part.
    BatchItem:
      type: object
      required:
        - manufacturerId
        - manufacturerPartId
        - batchId
        - catenaxId
      properties:
        manufacturerId:
          type: string
          example: "BPNL00000003BW3S"
          description: The Business Partner Number (BPNL) of the manufacturer of the batch, i.e., the companies main entry.
        manufacturerPartId:
          type: string
          example: "8840838-04"
          description: The ID of the type/catalog part (of which the batch is an instance of) from the manufacturer.
        customerPartId:
          type: string
          example: "AAX178378"
          description: The ID of the type/catalog part (of which the batch is an instance of) from the customer.
        batchId:
          type: string
          example: "NO-009284492099792129568369"
          description: The serial number of the batch from the manufacturer. We assume here that the customer does not have or create its own serial number for a batch, but just used the manufacturer's serial number.
        catenaxId:
          type: string
          example: "urn:uuid:d32d3b55-d222-41e9-8d19-554af53124dd"
          description: Catena-X ID for a batch.
